package gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.DBModel;
import model.IModel;

public class Foablak extends javax.swing.JFrame {

    private IModel model;

    
    public static void hibaAblak(String uzenet){
        JOptionPane.showMessageDialog(null, uzenet, "Hiba történt", JOptionPane.ERROR_MESSAGE);
    }
    
    public Foablak() {
        initComponents();

        UIManager.put("OptionPane.yesButtonText", "Igen");
        UIManager.put("OptionPane.noButtonText", "Nem");
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sajatClose();
            }            
        });     
        
        setLocationRelativeTo(null);
        setTitle("Megrendeléseket kezelő program v.0.1");
        
        
        String connURL = "jdbc:mysql://localhost:3306/megrendelesek";
        String dBuser = "root";
        String dBPass = "1234";
        
        try {
            Connection conn = DriverManager.getConnection(connURL, dBuser, dBPass);     
            model = new DBModel(conn);     
        } catch (SQLException ex) {
            hibaAblak(ex.toString());
            System.exit(-1);
        }
    }
    
    public void sajatClose(){
        try {
            model.close();
            //System.out.println("DB conn. lezárva");
        } catch (SQLException ex) {
            hibaAblak(ex.toString());            
        }
        System.exit(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        miKilepes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miSzemelyek = new javax.swing.JMenuItem();
        miMegrendelesek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Fájl");

        jMenuItem1.setText("Exportálás");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        miKilepes.setText("Kilépés");
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(miKilepes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Adatok");

        miSzemelyek.setText("Személyek");
        miSzemelyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSzemelyekActionPerformed(evt);
            }
        });
        jMenu2.add(miSzemelyek);

        miMegrendelesek.setText("Megrendelések");
        miMegrendelesek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMegrendelesekActionPerformed(evt);
            }
        });
        jMenu2.add(miMegrendelesek);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miMegrendelesekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMegrendelesekActionPerformed
      MegrendelesekDialog md = new MegrendelesekDialog(this, true, model);
      md.setVisible(true);
    }//GEN-LAST:event_miMegrendelesekActionPerformed

    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
       sajatClose();
    }//GEN-LAST:event_miKilepesActionPerformed

    private void miSzemelyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSzemelyekActionPerformed
        SzemelyekDialog szd = new SzemelyekDialog(this, true, model);
        szd.setVisible(true);
        
       
    }//GEN-LAST:event_miSzemelyekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miMegrendelesek;
    private javax.swing.JMenuItem miSzemelyek;
    // End of variables declaration//GEN-END:variables
}
