package gui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.Rendeles;
import model.Szemely;

public class MegrendelesAdatokDialog extends javax.swing.JDialog {

    /**
     * Creates new form MegrendelesAdatokDialog
     */
    private boolean mentes;
    private Rendeles rendeles;

    public MegrendelesAdatokDialog(java.awt.Frame parent, boolean modal, List<Szemely> szemelyek, Szemely megrendelo) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(parent);
        setTitle("Megrendelés felvétele");
        cbSzemelyek.setModel(new DefaultComboBoxModel<>(szemelyek.toArray()));
        cbSzemelyek.setSelectedItem(megrendelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbSzemelyek = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        chbTeljesitve = new javax.swing.JCheckBox();
        btnMegsem = new javax.swing.JButton();
        btnMentes = new javax.swing.JButton();
        tfOsszeg = new javax.swing.JTextField();
        tfDarabszam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Megrendelő:");

        jLabel2.setText("Összeg:");

        cbSzemelyek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Darabszám:");

        chbTeljesitve.setText("Teljesítve:        ");
        chbTeljesitve.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chbTeljesitve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTeljesitveActionPerformed(evt);
            }
        });

        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        tfDarabszam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDarabszamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfDarabszam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfOsszeg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSzemelyek, 0, 252, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chbTeljesitve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnMegsem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMentes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbSzemelyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(tfDarabszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMegsem)
                            .addComponent(btnMentes)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbTeljesitve)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbTeljesitveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTeljesitveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbTeljesitveActionPerformed

    private void tfDarabszamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDarabszamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDarabszamActionPerformed

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed
        Szemely megrendelo = (Szemely) cbSzemelyek.getSelectedItem();
        
        rendeles = new Rendeles();
        rendeles.setRendeloId(megrendelo.getId());
        rendeles.setOsszeg(Integer.parseInt(tfOsszeg.getText()));        
        rendeles.setDarabszam(Integer.parseInt(tfDarabszam.getText()));
        rendeles.setTeljesitve(chbTeljesitve.isSelected());
        
        mentes = true;
        setVisible(false);
    }//GEN-LAST:event_btnMentesActionPerformed

    public boolean isMentes() {
        return mentes;
    }

    public Rendeles getRendeles() {
        return rendeles;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.JComboBox cbSzemelyek;
    private javax.swing.JCheckBox chbTeljesitve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfDarabszam;
    private javax.swing.JTextField tfOsszeg;
    // End of variables declaration//GEN-END:variables
}
