package gui;

import java.awt.Frame;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.IModel;
import model.Szemely;

public class SzemelyekDialog extends javax.swing.JDialog {

    private IModel model;
    private Frame parent;

    public SzemelyekDialog(java.awt.Frame parent, boolean modal, IModel model) {
        super(parent, modal);
        initComponents();

        this.model = model;
        this.parent = parent;

        setLocationRelativeTo(parent);
        setTitle("Személyek kezelése");

        listaFrissit();
    }

    public void listaFrissit() {
        try {
            List<Szemely> szemelyek = model.getAllSzemely();

            lstSzemelyek.setListData(szemelyek.toArray());
        } catch (SQLException ex) {
            Foablak.hibaAblak(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstSzemelyek = new javax.swing.JList();
        btnUj = new javax.swing.JButton();
        btnSzerkeszt = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstSzemelyek.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstSzemelyek);

        btnUj.setText("Új");
        btnUj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjActionPerformed(evt);
            }
        });

        btnSzerkeszt.setText("Szerkeszt");
        btnSzerkeszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzerkesztActionPerformed(evt);
            }
        });

        btnTorol.setText("Töröl");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUj)
                    .addComponent(btnSzerkeszt)
                    .addComponent(btnTorol)
                    .addComponent(btnOK))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnOK, btnSzerkeszt, btnTorol, btnUj});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnUj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSzerkeszt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTorol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        Szemely kivalasztott = (Szemely) lstSzemelyek.getSelectedValue();

        if (kivalasztott != null) {
            int valasz = JOptionPane.showConfirmDialog(parent, "Biztosan törölni akarod?",
                    "Törlési megerőssítés", JOptionPane.YES_NO_OPTION);
            if (valasz == JOptionPane.YES_OPTION) {
                try {
                    model.removeSzemely(kivalasztott);
                    listaFrissit();
                } catch (SQLException ex) {
                    Foablak.hibaAblak(ex.toString());
                }
            }
        } else {
            Foablak.hibaAblak("Válassz ki valakit a törléshez!");
        }
    }//GEN-LAST:event_btnTorolActionPerformed

    private void btnUjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjActionPerformed
        SzemelyAdatokDialog szad = new SzemelyAdatokDialog(parent, true, null);
        szad.setVisible(true);

        if (szad.isMentes()) {
            try {
                //adatbázisba beszúrás
                Szemely sz = szad.getSzemely();
                model.addSzemely(sz);
                listaFrissit();
            } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        }
    }//GEN-LAST:event_btnUjActionPerformed

    private void btnSzerkesztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzerkesztActionPerformed
        Szemely kivalasztott = (Szemely) lstSzemelyek.getSelectedValue();
        if (kivalasztott != null) {
            SzemelyAdatokDialog szad = new SzemelyAdatokDialog(parent, true, kivalasztott);
            szad.setVisible(true);

            //adatbázisban módosítás
            if (szad.isMentes()) {
                try {
                    //kivalasztott = szad.getSzemely();   nem szükséges, mert ezt az objektumot adtuk át szerkesztésre
                    model.updateSzemely(kivalasztott);
                    listaFrissit();
                } catch (SQLException ex) {
                    Foablak.hibaAblak(ex.toString());
                }
                
            }
        } else {
            Foablak.hibaAblak("Válassz ki valakit a szerkesztéshez!");
        }

    }//GEN-LAST:event_btnSzerkesztActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSzerkeszt;
    private javax.swing.JButton btnTorol;
    private javax.swing.JButton btnUj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstSzemelyek;
    // End of variables declaration//GEN-END:variables
}
