package model;
// Generated 2018.12.01. 11:54:42 by Hibernate Tools 4.3.1



/**
 * Countrylanguage generated by hbm2java
 */
public class Countrylanguage  implements java.io.Serializable {


     private CountrylanguageId id;
     private Country country;
     private char isOfficial;
     private float percentage;

    public Countrylanguage() {
    }

    public Countrylanguage(CountrylanguageId id, Country country, char isOfficial, float percentage) {
       this.id = id;
       this.country = country;
       this.isOfficial = isOfficial;
       this.percentage = percentage;
    }
   
    public CountrylanguageId getId() {
        return this.id;
    }
    
    public void setId(CountrylanguageId id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public char getIsOfficial() {
        return this.isOfficial;
    }
    
    public void setIsOfficial(char isOfficial) {
        this.isOfficial = isOfficial;
    }
    public float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }




}


