package swinglampa;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;

public class Rajzlap extends javax.swing.JPanel {

    private LampaModel model;

    public Rajzlap() {
        initComponents();

        model = new LampaModel(true, false, false);

        getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke('p'), "piros");
        getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke('s'), "sarga");
        getInputMap(WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke('z'), "zold");

        getActionMap().put("piros", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                model.pirosKapcsol();
                repaint();
            }
        });

        getActionMap().put("sarga", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                model.sargaKapcsol();
                repaint();
            }
        });
        getActionMap().put("zold", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                model.zoldKapcsol();
                repaint();
            }
        });
        
        VezerloSzal vsz = new VezerloSzal(model, this);
        vsz.start(); 
       
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.BLACK);
        g.fillRect(40, 40, 80, 220);

        g.setColor(Color.red);
        if (model.isPiros()) {
            g.fillOval(50, 50, 60, 60);
        } else {
            g.drawOval(50, 50, 60, 60);
        }

        g.setColor(Color.YELLOW);
        if (model.isSarga()) {
            g.fillOval(50, 120, 60, 60);
        } else {
            g.drawOval(50, 120, 60, 60);
        }

        g.setColor(Color.GREEN);
        if (model.isZold()) {
            g.fillOval(50, 190, 60, 60);
        } else {
            g.drawOval(50, 190, 60, 60);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
